<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE easygradepro [
  <!ELEMENT easygradepro (gradebookinfo,class*)>
  <!ATTLIST easygradepro appversion CDATA #REQUIRED >
  <!ATTLIST easygradepro appos (mac|win) #REQUIRED >
  <!ELEMENT gradebookinfo (gb_filename, gb_date, gb_time, gb_termlabels, gb_classrecordlabels, gb_studentrecordlabels, gb_standardlevels, gb_comments )>
  <!ELEMENT gb_filename (#PCDATA)>
  <!ELEMENT gb_date (#PCDATA)>
  <!ELEMENT gb_time (#PCDATA)>
  <!ELEMENT gb_termlabels (gb_termlabel+)>
  <!ELEMENT gb_termlabel (#PCDATA)>
  <!ELEMENT gb_classrecordlabels (gb_classrecordlabel+)>
  <!ELEMENT gb_classrecordlabel (#PCDATA)>
  <!ELEMENT gb_studentrecordlabels (gb_studentrecordlabel+)>
  <!ELEMENT gb_studentrecordlabel (#PCDATA)>
  <!ELEMENT gb_standardlevels (gb_stdlevelname+)>
  <!ELEMENT gb_stdlevelname (#PCDATA)>
  <!ELEMENT gb_comments (gb_commenttext+)>
  <!ELEMENT gb_commenttext (#PCDATA)>
  <!ELEMENT class (classrecord, gradescales, rubrics, categories, footnotes, specialscores, attendancemastercats, attendancecodes, calendaroptions, termoptions, standards, assignments, student* )>
  <!ELEMENT classrecord (cr_classsubjectname, cr_termnum, cr_termlabel, cr_data+)>
  <!ELEMENT cr_classsubjectname (#PCDATA)>
  <!ELEMENT cr_termnum (#PCDATA)>
  <!ELEMENT cr_termlabel (#PCDATA)>
  <!ELEMENT cr_data (#PCDATA)>
  <!ATTLIST cr_data label CDATA #REQUIRED >
  <!ELEMENT gradescales (gs_scale+)>
  <!ATTLIST gradescales rounding (WholeNumber|Tenths|Hundredths) #REQUIRED >
  <!ELEMENT gs_scale (gs_id, gs_grades)>
  <!ELEMENT gs_id (#PCDATA)>
  <!ELEMENT gs_grades (grade+)>
  <!ELEMENT grade (gs_label, gs_minpct)>
  <!ELEMENT gs_label (#PCDATA)>
  <!ELEMENT gs_minpct (#PCDATA)>
  <!ELEMENT rubrics (rs_rubric+)>
  <!ATTLIST rubrics rounding (WholeNumber|Tenths|Hundredths) #REQUIRED >
  <!ELEMENT rs_rubric (rs_id, rs_items)>
  <!ELEMENT rs_id (#PCDATA)>
  <!ELEMENT rs_items (rs_item+)>
  <!ELEMENT rs_item (rs_label, rs_value)>
  <!ELEMENT rs_label (#PCDATA)>
  <!ELEMENT rs_value (#PCDATA)>
  <!ELEMENT categories (category+)>
  <!ELEMENT category (cat_id, cat_name, cat_weight, cat_gradescaleid, cat_other)>
  <!ELEMENT cat_id (#PCDATA)>
  <!ELEMENT cat_name (#PCDATA)>
  <!ELEMENT cat_weight (#PCDATA)>
  <!ELEMENT cat_gradescaleid (#PCDATA)>
  <!ELEMENT cat_other (#PCDATA)>
  <!ELEMENT footnotes (footnote+)>
  <!ELEMENT footnote (fn_id, fn_text )>
  <!ELEMENT fn_id (#PCDATA)>
  <!ELEMENT fn_text (#PCDATA)>
  <!ELEMENT specialscores (ss_score+)>
  <!ELEMENT ss_score (ss_name, ss_code, ss_shortcut, ss_pct, ss_missing )>
  <!ELEMENT ss_name (#PCDATA)>
  <!ELEMENT ss_code (#PCDATA)>
  <!ELEMENT ss_shortcut (#PCDATA)>
  <!ELEMENT ss_pct (#PCDATA)>
  <!ELEMENT ss_missing (#PCDATA)>
  <!ELEMENT attendancemastercats (at_mastercat+)>
  <!ELEMENT at_mastercat (at_masterid, at_mastername )>
  <!ELEMENT at_masterid (#PCDATA)>
  <!ELEMENT at_mastername (#PCDATA)>
  <!ELEMENT attendancecodes (at_code+)>
  <!ELEMENT at_code (at_symbol, at_cat_sub, at_cat_master, at_value, at_autofill)>
  <!ELEMENT at_symbol (#PCDATA)>
  <!ELEMENT at_cat_sub (#PCDATA)>
  <!ELEMENT at_cat_master (#PCDATA)>
  <!ELEMENT at_value (#PCDATA)>
  <!ELEMENT at_autofill (#PCDATA)>
  <!ELEMENT calendaroptions (cal_daysofweek+, cal_termstartdate, cal_termenddate, cal_termnoschooldays*)>
  <!ELEMENT cal_daysofweek (day+)>
  <!ELEMENT day (#PCDATA)>
  <!ATTLIST day id (1|2|3|4|5|6|7) #REQUIRED >
  <!ELEMENT cal_termstartdate (#PCDATA)>
  <!ELEMENT cal_termenddate (#PCDATA)>
  <!ELEMENT cal_termnoschooldays (cal_noschoolday*)>
  <!ELEMENT cal_noschoolday (#PCDATA)>
  <!ELEMENT termoptions (term_data*)>
  <!ELEMENT term_data (term_number, term_classname, term_weight)>
  <!ELEMENT term_number (#PCDATA)>
  <!ELEMENT term_classname (#PCDATA)>
  <!ELEMENT term_weight (#PCDATA)>
  <!ELEMENT standards (standard*)>
  <!ELEMENT standard (std_id, std_level, std_linkid, std_text, std_note, std_progressreport, std_rubric, std_gradingmethod, std_weight)>
  <!ELEMENT std_id (#PCDATA)>
  <!ELEMENT std_level (#PCDATA)>
  <!ELEMENT std_linkid (#PCDATA)>
  <!ELEMENT std_text (#PCDATA)>
  <!ELEMENT std_note (#PCDATA)>
  <!ELEMENT std_progressreport (#PCDATA)>
  <!ELEMENT std_rubric (#PCDATA)>
  <!ELEMENT std_gradingmethod (#PCDATA)>
  <!ELEMENT std_weight (#PCDATA)>
  <!ELEMENT assignments (assignment*)>
  <!ELEMENT assignment (ass_id, ass_name, ass_maxscore, ass_points, ass_date, ass_catid, ass_catname, ass_status, ass_display, ass_progressreport, ass_note, ass_standards)>
  <!ELEMENT ass_id (#PCDATA)>
  <!ELEMENT ass_name (#PCDATA)>
  <!ELEMENT ass_maxscore (#PCDATA)>
  <!ELEMENT ass_points (#PCDATA)>
  <!ELEMENT ass_date (#PCDATA)>
  <!ELEMENT ass_catid (#PCDATA)>
  <!ELEMENT ass_catname (#PCDATA)>
  <!ELEMENT ass_status (#PCDATA)>
  <!ELEMENT ass_display (#PCDATA)>
  <!ELEMENT ass_progressreport (#PCDATA)>
  <!ELEMENT ass_note (#PCDATA)>
  <!ELEMENT ass_standards (ass_stdid*)>
  <!ELEMENT ass_stdid (#PCDATA)>
  <!ELEMENT student (stud_recordinfo, stud_summarycomments, stud_summarynote, stud_grades, stud_attendance)>
  <!ELEMENT stud_recordinfo (stud_id, stud_status, stud_displayname, stud_lastname, stud_firstname, stud_gradescaleid, stud_gender, stud_data+)>
  <!ELEMENT stud_id (#PCDATA)>
  <!ELEMENT stud_status (#PCDATA)>
  <!ELEMENT stud_displayname (#PCDATA)>
  <!ELEMENT stud_lastname (#PCDATA)>
  <!ELEMENT stud_firstname (#PCDATA)>
  <!ELEMENT stud_gradescaleid (#PCDATA)>
  <!ELEMENT stud_gender (#PCDATA)>
  <!ELEMENT stud_data (#PCDATA)>
  <!ATTLIST stud_data label CDATA #REQUIRED >
  <!ELEMENT stud_summarycomments (stud_comment*)>
  <!ELEMENT stud_comment (#PCDATA)>
  <!ATTLIST stud_comment item (1|2|3|4|5|6) #REQUIRED >
  <!ELEMENT stud_summarynote (#PCDATA)>
  <!ELEMENT stud_grades (score*, overall, termgrades*, stud_stdgrades*)>
  <!ELEMENT score (score_raw, score_percent, score_grade,score_note*)>
  <!ATTLIST score assid CDATA #REQUIRED >
  <!ELEMENT score_raw (#PCDATA)>
  <!ELEMENT score_percent (#PCDATA)>
  <!ELEMENT score_grade (#PCDATA)>
  <!ELEMENT score_note (#PCDATA)>
  <!ELEMENT overall (overall_percent, overall_points, overall_grade)>
  <!ELEMENT overall_percent (#PCDATA)>
  <!ELEMENT overall_points (#PCDATA)>
  <!ELEMENT overall_grade (#PCDATA)>
  <!ELEMENT termgrades (termgrade*)>
  <!ELEMENT termgrade (term_num, term_percent, term_points, term_grade)>
  <!ELEMENT term_num (#PCDATA)>
  <!ELEMENT term_percent (#PCDATA)>
  <!ELEMENT term_points (#PCDATA)>
  <!ELEMENT term_grade (#PCDATA)>
  <!ELEMENT stud_stdgrades (stud_stdoverall, stud_stdgrade*)>
  <!ELEMENT stud_stdoverall (stud_stdoverall_numericgrade, stud_stdoverall_rubricgrade)>
  <!ELEMENT stud_stdoverall_numericgrade (#PCDATA)>
  <!ELEMENT stud_stdoverall_rubricgrade (#PCDATA)>
  <!ELEMENT stud_stdgrade (stud_stdid, stud_numericgrade, stud_rubricgrade,stud_stdassignment*, stud_stdtermgrades*)>
  <!ELEMENT stud_stdid (#PCDATA)>
  <!ELEMENT stud_numericgrade (#PCDATA)>
  <!ELEMENT stud_rubricgrade (#PCDATA)>
  <!ELEMENT stud_stdassignment (stud_stdass_assid,stud_stdass_score,stud_stdass_grade)>
  <!ELEMENT stud_stdass_assid (#PCDATA)>
  <!ELEMENT stud_stdass_score (#PCDATA)>
  <!ELEMENT stud_stdass_grade (#PCDATA)>
  <!ELEMENT stud_stdtermgrades (stud_stdtermgrade*)>
  <!ELEMENT stud_stdtermgrade (stud_stdterm_number, stud_stdterm_numericgrade, stud_stdterm_rubricgrade)>
  <!ELEMENT stud_stdterm_number (#PCDATA)>
  <!ELEMENT stud_stdterm_numericgrade (#PCDATA)>
  <!ELEMENT stud_stdterm_rubricgrade (#PCDATA)>
  <!ELEMENT stud_attendance (stud_attitem*,stud_att_totals, stud_att_termtotals*)>
  <!ELEMENT stud_attitem (stud_attcode, stud_attdate ) >
  <!ELEMENT stud_attcode (#PCDATA)>
  <!ELEMENT stud_attdate (#PCDATA)>
  <!ELEMENT stud_att_totals (stud_att_mastercat, stud_att_code*)* >
  <!ELEMENT stud_att_mastercat (#PCDATA)>
  <!ATTLIST stud_att_mastercat cat CDATA #REQUIRED >
  <!ELEMENT stud_att_code (#PCDATA)>
  <!ATTLIST stud_att_code code CDATA #REQUIRED >
  <!ELEMENT stud_att_termtotals (at_total_term, at_total*) >
  <!ELEMENT at_total_term (#PCDATA)>
  <!ELEMENT at_total (#PCDATA)>
  <!ATTLIST at_total code CDATA #REQUIRED >
]>

<easygradepro appversion="4.0.3.15" appos="win">
  <gradebookinfo>
    <gb_filename>Homeroom Sample.EGP</gb_filename>
    <gb_date>6/22/2010</gb_date>
    <gb_time>6:29 AM</gb_time>
    <gb_termlabels>
      <gb_termlabel>Term 1</gb_termlabel>
      <gb_termlabel>Term 2</gb_termlabel>
      <gb_termlabel>Term 3</gb_termlabel>
      <gb_termlabel>Term 4</gb_termlabel>
      <gb_termlabel>Term 5</gb_termlabel>
      <gb_termlabel>Term 6</gb_termlabel>
      <gb_termlabel>Term 7</gb_termlabel>
      <gb_termlabel>Term 8</gb_termlabel>
      <gb_termlabel>Term 9</gb_termlabel>
      <gb_termlabel>Term 10</gb_termlabel>
    </gb_termlabels>
    <gb_classrecordlabels>
      <gb_classrecordlabel>SubjectID</gb_classrecordlabel>
      <gb_classrecordlabel>SubjectName</gb_classrecordlabel>
      <gb_classrecordlabel>SubjectCategory</gb_classrecordlabel>
      <gb_classrecordlabel>Level</gb_classrecordlabel>
      <gb_classrecordlabel>Section</gb_classrecordlabel>
      <gb_classrecordlabel>Adviser</gb_classrecordlabel>
      <gb_classrecordlabel>Custom 7</gb_classrecordlabel>
      <gb_classrecordlabel>Custom 8</gb_classrecordlabel>
    </gb_classrecordlabels>
    <gb_studentrecordlabels>
      <gb_studentrecordlabel>Level</gb_studentrecordlabel>
      <gb_studentrecordlabel>Section</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 3</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 4</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 5</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 6</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 7</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 8</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 9</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 10</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 11</gb_studentrecordlabel>
      <gb_studentrecordlabel>Custom 12</gb_studentrecordlabel>
    </gb_studentrecordlabels>
    <gb_standardlevels>
      <gb_stdlevelname>Standard</gb_stdlevelname>
      <gb_stdlevelname>Strand</gb_stdlevelname>
      <gb_stdlevelname>Indicator</gb_stdlevelname>
    </gb_standardlevels>
    <gb_comments>
      <gb_commenttext>^ is doing excellent work.</gb_commenttext>
      <gb_commenttext>^ is a pleasure to have in class.</gb_commenttext>
      <gb_commenttext>^ is a conscientious and dependable student.</gb_commenttext>
      <gb_commenttext>^ is progressing satisfactorily.</gb_commenttext>
      <gb_commenttext>^ is showing improvement.</gb_commenttext>
      <gb_commenttext>^ needs to improve work habits.</gb_commenttext>
      <gb_commenttext>^ does not do homework regularly.</gb_commenttext>
      <gb_commenttext>Classroom behavior needs to be improved.</gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
      <gb_commenttext> </gb_commenttext>
    </gb_comments>
  </gradebookinfo>

  <class>
    <classrecord>
      <cr_classsubjectname>Homeroom</cr_classsubjectname>
      <cr_termnum>1</cr_termnum>
      <cr_termlabel>Term 1</cr_termlabel>
      <cr_data label="SubjectID">Homeroom</cr_data>
      <cr_data label="SubjectName">HOMEROOM</cr_data>
      <cr_data label="SubjectCategory">HOMEROOM</cr_data>
      <cr_data label="Level"> </cr_data>
      <cr_data label="Section"> </cr_data>
      <cr_data label="Adviser"> </cr_data>
      <cr_data label="Custom 7"> </cr_data>
      <cr_data label="Custom 8"> </cr_data>
    </classrecord>

    <gradescales rounding="Tenths">
      <gs_scale>
        <gs_id>1</gs_id>
        <gs_grades>
          <grade>
            <gs_label>VS</gs_label>
            <gs_minpct>96</gs_minpct>
          </grade>
          <grade>
            <gs_label>S</gs_label>
            <gs_minpct>91</gs_minpct>
          </grade>
          <grade>
            <gs_label>AA</gs_label>
            <gs_minpct>85</gs_minpct>
          </grade>
          <grade>
            <gs_label>A</gs_label>
            <gs_minpct>80</gs_minpct>
          </grade>
          <grade>
            <gs_label>LA</gs_label>
            <gs_minpct>75</gs_minpct>
          </grade>
          <grade>
            <gs_label>P</gs_label>
            <gs_minpct>70</gs_minpct>
          </grade>
          <grade>
            <gs_label>INC</gs_label>
            <gs_minpct>0</gs_minpct>
          </grade>
        </gs_grades>
      </gs_scale>
    </gradescales>

    <rubrics rounding="Tenths">
      <rs_rubric>
        <rs_id>1</rs_id>
        <rs_items>
          <rs_item>
            <rs_label>Exceeds Standard</rs_label>
            <rs_value>4.00</rs_value>
          </rs_item>
          <rs_item>
            <rs_label>Meets Standard</rs_label>
            <rs_value>3.00</rs_value>
          </rs_item>
          <rs_item>
            <rs_label>Approaching Standard</rs_label>
            <rs_value>2.00</rs_value>
          </rs_item>
          <rs_item>
            <rs_label>Below Standard</rs_label>
            <rs_value>1.00</rs_value>
          </rs_item>
        </rs_items>
      </rs_rubric>
      <rs_rubric>
        <rs_id>2</rs_id>
        <rs_items>
          <rs_item>
            <rs_label>Excellent</rs_label>
            <rs_value>5.00</rs_value>
          </rs_item>
          <rs_item>
            <rs_label>Very Good</rs_label>
            <rs_value>4.00</rs_value>
          </rs_item>
          <rs_item>
            <rs_label>Good</rs_label>
            <rs_value>3.00</rs_value>
          </rs_item>
          <rs_item>
            <rs_label>Fair</rs_label>
            <rs_value>2.00</rs_value>
          </rs_item>
          <rs_item>
            <rs_label>Poor</rs_label>
            <rs_value>1.00</rs_value>
          </rs_item>
        </rs_items>
      </rs_rubric>
    </rubrics>

    <categories>
      <category>
        <cat_id>1</cat_id>
        <cat_name>Competence</cat_name>
        <cat_weight>20</cat_weight>
        <cat_gradescaleid>2</cat_gradescaleid>
        <cat_other> </cat_other>
      </category>
      <category>
        <cat_id>2</cat_id>
        <cat_name>Character</cat_name>
        <cat_weight>20</cat_weight>
        <cat_gradescaleid>2</cat_gradescaleid>
        <cat_other> </cat_other>
      </category>
      <category>
        <cat_id>3</cat_id>
        <cat_name>Commitment</cat_name>
        <cat_weight>20</cat_weight>
        <cat_gradescaleid>2</cat_gradescaleid>
        <cat_other> </cat_other>
      </category>
      <category>
        <cat_id>4</cat_id>
        <cat_name>Collaboration</cat_name>
        <cat_weight>20</cat_weight>
        <cat_gradescaleid>2</cat_gradescaleid>
        <cat_other> </cat_other>
      </category>
      <category>
        <cat_id>5</cat_id>
        <cat_name>Creativity</cat_name>
        <cat_weight>20</cat_weight>
        <cat_gradescaleid>2</cat_gradescaleid>
        <cat_other> </cat_other>
      </category>
      <category>
        <cat_id>6</cat_id>
        <cat_name>Remarks</cat_name>
        <cat_weight>0</cat_weight>
        <cat_gradescaleid>2</cat_gradescaleid>
        <cat_other> </cat_other>
      </category>
    </categories>

    <footnotes>
      <footnote>
        <fn_id>1</fn_id>
        <fn_text>Turned in late.</fn_text>
      </footnote>
      <footnote>
        <fn_id>2</fn_id>
        <fn_text>Score reduced because turned in late.</fn_text>
      </footnote>
      <footnote>
        <fn_id>3</fn_id>
        <fn_text>Score increased due to extra credit.</fn_text>
      </footnote>
      <footnote>
        <fn_id>4</fn_id>
        <fn_text>Score increased due to extra effort.</fn_text>
      </footnote>
      <footnote>
        <fn_id>5</fn_id>
        <fn_text>Has been encouraged to study and improve this score.</fn_text>
      </footnote>
      <footnote>
        <fn_id>6</fn_id>
        <fn_text>Would have been higher had homework been done.</fn_text>
      </footnote>
      <footnote>
        <fn_id>7</fn_id>
        <fn_text>Homework must be completed before test can be taken.</fn_text>
      </footnote>
      <footnote>
        <fn_id>8</fn_id>
        <fn_text> </fn_text>
      </footnote>
      <footnote>
        <fn_id>9</fn_id>
        <fn_text> </fn_text>
      </footnote>
    </footnotes>

    <specialscores>
      <ss_score>
        <ss_name>Excused</ss_name>
        <ss_code>ex</ss_code>
        <ss_shortcut>E</ss_shortcut>
        <ss_pct> </ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Credit</ss_name>
        <ss_code>cr</ss_code>
        <ss_shortcut>C</ss_shortcut>
        <ss_pct> </ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Absent</ss_name>
        <ss_code>ab</ss_code>
        <ss_shortcut>A</ss_shortcut>
        <ss_pct>0</ss_pct>
        <ss_missing>yes</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Missing</ss_name>
        <ss_code>mi</ss_code>
        <ss_shortcut>M</ss_shortcut>
        <ss_pct>0</ss_pct>
        <ss_missing>yes</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Incomplete</ss_name>
        <ss_code>inc</ss_code>
        <ss_shortcut>I</ss_shortcut>
        <ss_pct>0</ss_pct>
        <ss_missing>yes</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Yes</ss_name>
        <ss_code>yes</ss_code>
        <ss_shortcut>Y</ss_shortcut>
        <ss_pct>100</ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>No</ss_name>
        <ss_code>no</ss_code>
        <ss_shortcut>N</ss_shortcut>
        <ss_pct>0</ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Drop</ss_name>
        <ss_code>dr</ss_code>
        <ss_shortcut>D</ss_shortcut>
        <ss_pct> </ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Outstanding</ss_name>
        <ss_code>o</ss_code>
        <ss_shortcut>O</ss_shortcut>
        <ss_pct>100</ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Satisfactory</ss_name>
        <ss_code>s</ss_code>
        <ss_shortcut>S</ss_shortcut>
        <ss_pct>80</ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Unsatisfactory</ss_name>
        <ss_code>u</ss_code>
        <ss_shortcut>U</ss_shortcut>
        <ss_pct>60</ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
      <ss_score>
        <ss_name>Completed</ss_name>
        <ss_code>ok</ss_code>
        <ss_shortcut> </ss_shortcut>
        <ss_pct> </ss_pct>
        <ss_missing>no</ss_missing>
      </ss_score>
    </specialscores>

    <attendancemastercats>
      <at_mastercat>
        <at_masterid>1</at_masterid>
        <at_mastername>Excused Absence</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>2</at_masterid>
        <at_mastername>Unexcused Absence</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>3</at_masterid>
        <at_mastername>Tardy</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>4</at_masterid>
        <at_mastername>Other</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>5</at_masterid>
        <at_mastername>Master Cat 5</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>6</at_masterid>
        <at_mastername>Master Cat 6</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>7</at_masterid>
        <at_mastername>Master Cat 7</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>8</at_masterid>
        <at_mastername>Master Cat 8</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>9</at_masterid>
        <at_mastername>Master Cat 9</at_mastername>
      </at_mastercat>
      <at_mastercat>
        <at_masterid>10</at_masterid>
        <at_mastername>Master Cat 10</at_mastername>
      </at_mastercat>
    </attendancemastercats>
    <attendancecodes>
      <at_code>
        <at_symbol>AE</at_symbol>
        <at_cat_sub>Absence</at_cat_sub>
        <at_cat_master>1</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>AH</at_symbol>
        <at_cat_sub>Half Day</at_cat_sub>
        <at_cat_master>1</at_cat_master>
        <at_value>0.50</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>AS</at_symbol>
        <at_cat_sub>Suspension</at_cat_sub>
        <at_cat_master>1</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>UA</at_symbol>
        <at_cat_sub>Absence</at_cat_sub>
        <at_cat_master>2</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>UH</at_symbol>
        <at_cat_sub>Half Day</at_cat_sub>
        <at_cat_master>2</at_cat_master>
        <at_value>0.50</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>TE</at_symbol>
        <at_cat_sub>Excused</at_cat_sub>
        <at_cat_master>3</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>TU</at_symbol>
        <at_cat_sub>Unexcused</at_cat_sub>
        <at_cat_master>3</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>OA</at_symbol>
        <at_cat_sub>School Absence</at_cat_sub>
        <at_cat_master>4</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>OI</at_symbol>
        <at_cat_sub>Infirmary</at_cat_sub>
        <at_cat_master>4</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
      <at_code>
        <at_symbol>ON</at_symbol>
        <at_cat_sub>Not Enrolled</at_cat_sub>
        <at_cat_master>4</at_cat_master>
        <at_value>1.00</at_value>
        <at_autofill></at_autofill>
      </at_code>
    </attendancecodes>

    <calendaroptions>
      <cal_daysofweek>
        <day id="1">no</day>
        <day id="2">yes</day>
        <day id="3">yes</day>
        <day id="4">yes</day>
        <day id="5">yes</day>
        <day id="6">yes</day>
        <day id="7">no</day>
      </cal_daysofweek>
      <cal_termstartdate>5/4/2010</cal_termstartdate>
      <cal_termenddate>5/31/2010</cal_termenddate>
      <cal_termnoschooldays>
      </cal_termnoschooldays>
    </calendaroptions>

    <termoptions>
    </termoptions>

    <standards>
    </standards>
    <assignments>
      <assignment>
        <ass_id>1</ass_id>
        <ass_name>A1Performs with Int&apos;l Standards</ass_name>
        <ass_maxscore>100</ass_maxscore>
        <ass_points>100</ass_points>
        <ass_date>5/3/2010</ass_date>
        <ass_catid>1</ass_catid>
        <ass_catname>Competence</ass_catname>
        <ass_status>Normal</ass_status>
        <ass_display>Raw Scores</ass_display>
        <ass_progressreport>Include Assignment</ass_progressreport>
        <ass_note>Performs at least on a par with international standards in the core subjects</ass_note>
        <ass_standards>
        </ass_standards>
      </assignment>
      <assignment>
        <ass_id>2</ass_id>
        <ass_name>A2 Solves problems, mult-disp</ass_name>
        <ass_maxscore>100</ass_maxscore>
        <ass_points>100</ass_points>
        <ass_date>5/3/2010</ass_date>
        <ass_catid>1</ass_catid>
        <ass_catname>Competence</ass_catname>
        <ass_status>Normal</ass_status>
        <ass_display>Raw Scores</ass_display>
        <ass_progressreport>Include Assignment</ass_progressreport>
        <ass_note>Solves problems and completes tasks using multi-disciplinary skills</ass_note>
        <ass_standards>
        </ass_standards>
      </assignment>
      <assignment>
        <ass_id>3</ass_id>
        <ass_name>A3 Integrates and applies knowl</ass_name>
        <ass_maxscore>100</ass_maxscore>
        <ass_points>100</ass_points>
        <ass_date>5/3/2010</ass_date>
        <ass_catid>1</ass_catid>
        <ass_catname>Competence</ass_catname>
        <ass_status>Normal</ass_status>
        <ass_display>Raw Scores</ass_display>
        <ass_progressreport>Include Assignment</ass_progressreport>
        <ass_note>Integrates and applies knowledge gained from subjects into real life situations</ass_note>
        <ass_standards>
        </ass_standards>
      </assignment>
      <assignment>
        <ass_id>4</ass_id>
        <ass_name>A4 Expresses ideas clearly and</ass_name>
        <ass_maxscore>100</ass_maxscore>
        <ass_points>100</ass_points>
        <ass_date>5/3/2010</ass_date>
        <ass_catid>1</ass_catid>
        <ass_catname>Competence</ass_catname>
        <ass_status>Normal</ass_status>
        <ass_display>Raw Scores</ass_display>
        <ass_progressreport>Include Assignment</ass_progressreport>
        <ass_note>Expresses ideas clearly and effectively in oral and written communication</ass_note>
        <ass_standards>
        </ass_standards>
      </assignment>
      <assignment>
        <ass_id>5</ass_id>